### ISSUE TITLE
ddos


### ISSUE THREAD

**Issue by Wdoyok** [TermuxHackz/Hammer#1]

**Comment by frankygoodkidtho5555** [comment]
will the hammer tool also shut down the web addresses on your phone for wich you can browse or only outside devices? cause like when i was like testing it for example the ip address for facebook.com and i was able to browse facebook.com just perfectly on my device? @TermuxHackz

**Comment by khansaad1275** [comment]
> 

You can't just DDOS any website. These small tools only work with small website or blogs (if they work)

**Comment by akacrazy07** [comment]
no bro, there are some sites that are hosted on cloudfare servers (for example), so you can't do ddos, because they are protected against ddos

**Comment by akacrazy07** [comment]
I recommend using an ip lockup to find out if the site is DDOS protected, just see the info :)
